Repository 2025-DB-team-join/Gatcha, pull requests merged in 2025-05, with the labels that each got.

#2 [FEAT] DBConnector 추가
  src/main/java/gotcha/Main.java
  src/main/java/gotcha/common/DBConnector.java
  src/main/java/gotcha/common/FontLoader.java
Labels: enhancement

#3 docs: issue template 추가
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/help_request.md
Labels: documentation

#21 [FEAT] dummy db insertion
  src/main/resources/db/_localhost___AS-2025_05_15_13_58_25-dump.sql
Labels: documentation

#24 [FEAT] 전역 폰트 적용
  src/main/java/gotcha/Main.java
  src/main/java/gotcha/common/FontLoader.java
  src/main/java/gotcha/ui/AuthScreen.java
Labels: enhancement

#22 [FEAT] 이메일 중복 체크 dao 추가, 회원가입 로직 초기 구현 closed #4
  src/main/java/gotcha/dao/TagDAO.java
  src/main/java/gotcha/dao/UserDAO.java
  src/main/java/gotcha/service/TagService.java
  src/main/java/gotcha/service/UserService.java
  src/main/java/gotcha/ui/AuthScreen.java
  src/main/java/gotcha/ui/TagSelectionScreen.java
  src/main/resources/db/_localhost___AS-2025_05_16_16_02_15-dump.sql
Labels: enhancement

#25 [FEAT] 소모임 생성 기능 구현 및 화면 연결 (GroupFormScreen, HomeScreen)
  src/main/java/gotcha/common/Session.java
  src/main/java/gotcha/dao/GroupDAO.java
  src/main/java/gotcha/ui/GroupFormScreen.java
  src/main/java/gotcha/ui/HomeScreen.java
  src/test/java/gotcha/GroupFormScreenTest.java
  src/test/java/gotcha/HomeScreenTest.java
Labels: enhancement

#27 [REFACTOR] session 및 datelabelformatter 추가, close #12
  pom.xml
  src/main/java/gotcha/common/DateLabelFormatter.java
  src/main/java/gotcha/common/Session.java
  src/main/java/gotcha/ui/AuthScreen.java
  src/main/java/gotcha/ui/GroupFormScreen.java
  src/main/lib/jdatepicker-1.3.4.jar
Labels: documentation, duplicate, enhancement

#32 [FEAT] 소모임 카테고리별 조회
  src/main/java/gotcha/dao/CategoryDAO.java
  src/main/java/gotcha/dao/GroupDAO.java
  src/main/java/gotcha/service/CategoryService.java
  src/main/java/gotcha/service/GroupService.java
  src/main/java/gotcha/ui/CategoryScreen.java
  src/main/java/gotcha/ui/HomeScreen.java
Labels: enhancement

#40 [FEAT] 홈화면 출석률 기반 및 전체 소모임 조회 추가, close #23 Feature/30
  src/main/java/gotcha/service/GroupService.java
  src/main/java/gotcha/ui/HomeScreen.java
Labels: enhancement, help wanted

#39 [FEAT] user가 스크랩한 소모임 조회
  src/main/java/gotcha/dao/ScrapDAO.java
  src/main/java/gotcha/service/ScrapService.java
  src/main/java/gotcha/ui/ScrapListScreen.java
  src/test/java/gotcha/ScrapListScreenTest.java
Labels: enhancement

#34 [FEAT] 사용자가 설정한 지역, 성별 조건에 따라서, 가입자 수가 많은 순서대로 클래스 보여주는 창
  src/main/java/gotcha/dao/RegionGenderDAO.java
  src/main/java/gotcha/service/HomeService.java
  src/main/java/gotcha/service/RegionGenderService.java
  src/main/java/gotcha/ui/GroupFormScreen.java
  src/main/java/gotcha/ui/HomeScreen.java
  src/main/java/gotcha/ui/RegionGenderScreen.java
Labels: enhancement

#35 [FEAT] class status가 진행중인 class 중에 자신이 참여중인 목록들만 나오는 창. [refactor]있는데 표시된지 잘 모르겠네요
  src/main/java/gotcha/dao/CurrentGroupDAO.java
  src/main/java/gotcha/dao/UserDAO.java
  src/main/java/gotcha/service/CurrentGroupService.java
  src/main/java/gotcha/service/UserService.java
  src/main/java/gotcha/ui/CurrentGroupScreen.java
  src/main/java/gotcha/ui/HomeScreen.java
  src/main/java/gotcha/ui/MyPageScreen.java
Labels: enhancement

#41 feat: 마이페이지 정보 변경, 수정, 회원탈퇴 추가, closing #6 and #7
  src/main/java/gotcha/Main.java
  src/main/java/gotcha/dao/UserDAO.java
  src/main/java/gotcha/service/UserService.java
  src/main/java/gotcha/ui/BoardWriteScreen.java
  src/main/java/gotcha/ui/GroupFormScreen.java
  src/main/java/gotcha/ui/GroupScreen.java
  src/main/java/gotcha/ui/home/AuthScreen.java
  src/main/java/gotcha/ui/home/HomeScreen.java
  src/main/java/gotcha/ui/home/RegionGenderScreen.java
  src/main/java/gotcha/ui/home/TagSelectionScreen.java
  src/main/java/gotcha/ui/mypage/ChangePasswordDialog.java
  src/main/java/gotcha/ui/mypage/DeleteAccountDialog.java
  src/main/java/gotcha/ui/mypage/EditUserInfoDialog.java
  src/main/java/gotcha/ui/mypage/MyPageScreen.java
  src/test/java/gotcha/HomeScreenTest.java
Labels: enhancement
